### PR TITLE
add php ideas in how to approach project

### PR DESCRIPTION
**Pull request by IsaacJrTypes**

### CODE REVIEW

**Review by Matthieu-ui — CHANGES_REQUESTED** [review]
looks good! Simple and easy to follow, a good place to start I'd say. 
Can you throw a reset button on there?

**Review by Matthieu-ui — APPROVED** [review]

**Review by Matthieu-ui — APPROVED** [review]

**Review by Matthieu-ui — APPROVED** [review]

**Review by Matthieu-ui — APPROVED** [review]

**Review by Matthieu-ui — APPROVED** [review]

**Review by Matthieu-ui — APPROVED** [review]

**Review by Matthieu-ui — APPROVED** [review]

**Review by Matthieu-ui — APPROVED** [review]

**Review by Matthieu-ui — APPROVED** [review]

**Review by Matthieu-ui — APPROVED** [review]

**Review by Matthieu-ui — APPROVED** [review]

**Review by Matthieu-ui — APPROVED** [review]

**Review by Matthieu-ui — APPROVED** [review]

**Review by Matthieu-ui — APPROVED** [review]

**Review by Matthieu-ui — APPROVED** [review]

**Comment by IsaacJrTypes** [comment]
add button so webpage resets and moves vardump to bottom of webpage

**Comment by Matthieu-ui** [comment]
I think I am getting some weird glitch, can't merge, tried to merge from the command line and get the same thing "Commits must have valid signatures." have you seen this before?

**Review by Matthieu-ui — APPROVED** [review]
Nice good addition and progress. Something we need to keep in mind and add is checking if the checkbox is checked, keeping the selections and ability to change them!

**Pull request merged**
